name = "gymmatrix"
main = "src/index.ts"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]

[[ d1_databases ]]
binding = "DB"
database_name = "gymmatrix-db"
database_id = "1f2eaa61-d59c-4060-9b09-c8f7ffb2a6eb"

[assets]
directory = "../frontend/dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = true

[dev]
port = 8787
local_protocol = "http"
