name = "gymmatrix"
main = "src/index.ts"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]

[[ d1_databases ]]
binding = "DB"
database_name = "gymmatrix-db"
database_id = "local-gymmatrix-db"

[assets]
directory = "../frontend/dist"
binding = "ASSETS"

[dev]
port = 8787
local_protocol = "http"
